-- WP21: official ABS demographic enrichment at ASGS Edition 3 SA2 2021.
-- Generated by scripts/import-abs-demographics.mjs from official CC BY 4.0 sources.
-- Census counts are not Estimated Resident Population and are never substituted for ERP.

INSERT INTO public.dispensing_demographic_sources (
  id,dataset_name,exact_source,source_url,licence,geography_level,boundary_edition,
  reference_year,fields_used,import_method,fetched_at,row_count
) VALUES
(
  '21000000-0000-4000-8000-000000000001',
  '2021 Census General Community Profile — Victoria SA2 short-header DataPack',
  'Australian Bureau of Statistics 2021 Census DataPacks, tables G01, G18 and G34',
  '__GCP_URL__',
  'Creative Commons Attribution 4.0 International',
  'Statistical Area Level 2','ASGS Edition 3 SA2 2021',2021,
  ARRAY[
    'Tot_P_P','Age_0_4_yr_P','Age_65_74_yr_P','Age_75_84_yr_P','Age_85ov_P',
    'P_Tot_Need_for_assistance','Num_MVs_per_dweling_0_MVs','Num_MVs_per_dweling_Tot'
  ],
  'Reproducible download and short-header CSV extraction; sha256 __GCP_SHA256__; '
    'blank, non-published and suppressed values remain null',
  '2026-07-29T04:30:00Z',522
),
(
  '21000000-0000-4000-8000-000000000002',
  'Socio-Economic Indexes for Areas (SEIFA), Australia, 2021 — SA2 indexes',
  'Australian Bureau of Statistics SEIFA 2021, SA2 tables 2 and 4',
  '__SEIFA_URL__',
  'Creative Commons Attribution 4.0 International',
  'Statistical Area Level 2','ASGS Edition 3 SA2 2021',2021,
  ARRAY[
    'IRSD score','IRSD state decile','IRSD state percentile',
    'IER score','IER state decile','IER state percentile'
  ],
  'Reproducible XLSX extraction; sha256 __SEIFA_SHA256__; excluded areas remain null',
  '2026-07-29T04:30:00Z',522
)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE public.demographic_area_profiles (
  sa2_code_2021 TEXT NOT NULL,
  reference_year INTEGER NOT NULL,
  sa2_name_2021 TEXT NOT NULL,
  geography_level TEXT NOT NULL DEFAULT 'SA2',
  boundary_edition TEXT NOT NULL DEFAULT 'ASGS Edition 3 SA2 2021',
  census_total_population NUMERIC,
  age_65_plus_count NUMERIC,
  age_65_plus_percent NUMERIC,
  age_75_plus_count NUMERIC,
  age_75_plus_percent NUMERIC,
  under_five_count NUMERIC,
  under_five_percent NUMERIC,
  need_assistance_count NUMERIC,
  need_assistance_percent NUMERIC,
  no_vehicle_dwellings_count NUMERIC,
  vehicle_response_dwellings_count NUMERIC,
  no_vehicle_dwellings_percent NUMERIC,
  seifa_irsd_score NUMERIC,
  seifa_irsd_state_decile NUMERIC,
  seifa_irsd_state_percentile NUMERIC,
  seifa_ier_score NUMERIC,
  seifa_ier_state_decile NUMERIC,
  seifa_ier_state_percentile NUMERIC,
  census_source_id UUID NOT NULL REFERENCES public.dispensing_demographic_sources(id),
  seifa_source_id UUID NOT NULL REFERENCES public.dispensing_demographic_sources(id),
  coverage_status TEXT NOT NULL CHECK (coverage_status IN ('complete','partial','unavailable')),
  missing_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
  retrieved_at TIMESTAMPTZ NOT NULL DEFAULT '2026-07-29T04:30:00Z',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (sa2_code_2021,reference_year),
  FOREIGN KEY (sa2_code_2021) REFERENCES public.dispensing_population_areas(sa2_code_2021),
  CHECK (age_65_plus_percent IS NULL OR age_65_plus_percent BETWEEN 0 AND 100),
  CHECK (age_75_plus_percent IS NULL OR age_75_plus_percent BETWEEN 0 AND 100),
  CHECK (under_five_percent IS NULL OR under_five_percent BETWEEN 0 AND 100),
  CHECK (need_assistance_percent IS NULL OR need_assistance_percent BETWEEN 0 AND 100),
  CHECK (no_vehicle_dwellings_percent IS NULL OR no_vehicle_dwellings_percent BETWEEN 0 AND 100)
);

ALTER TABLE public.demographic_area_profiles ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.demographic_area_profiles TO anon,authenticated;
GRANT ALL ON public.demographic_area_profiles TO service_role;
CREATE POLICY public_reads_official_demographic_profiles
  ON public.demographic_area_profiles FOR SELECT TO anon,authenticated USING (true);

INSERT INTO public.demographic_area_profiles (
  sa2_code_2021,sa2_name_2021,census_total_population,
  age_65_plus_count,age_65_plus_percent,age_75_plus_count,age_75_plus_percent,
  under_five_count,under_five_percent,need_assistance_count,need_assistance_percent,
  no_vehicle_dwellings_count,vehicle_response_dwellings_count,no_vehicle_dwellings_percent,
  seifa_irsd_score,seifa_irsd_state_decile,seifa_irsd_state_percentile,
  seifa_ier_score,seifa_ier_state_decile,seifa_ier_state_percentile,
  coverage_status,missing_reasons,census_source_id,seifa_source_id
) VALUES
__DEMOGRAPHIC_ROWS__
ON CONFLICT (sa2_code_2021,reference_year) DO UPDATE SET
  census_total_population=EXCLUDED.census_total_population,
  age_65_plus_count=EXCLUDED.age_65_plus_count,
  age_65_plus_percent=EXCLUDED.age_65_plus_percent,
  age_75_plus_count=EXCLUDED.age_75_plus_count,
  age_75_plus_percent=EXCLUDED.age_75_plus_percent,
  under_five_count=EXCLUDED.under_five_count,
  under_five_percent=EXCLUDED.under_five_percent,
  need_assistance_count=EXCLUDED.need_assistance_count,
  need_assistance_percent=EXCLUDED.need_assistance_percent,
  no_vehicle_dwellings_count=EXCLUDED.no_vehicle_dwellings_count,
  vehicle_response_dwellings_count=EXCLUDED.vehicle_response_dwellings_count,
  no_vehicle_dwellings_percent=EXCLUDED.no_vehicle_dwellings_percent,
  seifa_irsd_score=EXCLUDED.seifa_irsd_score,
  seifa_irsd_state_decile=EXCLUDED.seifa_irsd_state_decile,
  seifa_irsd_state_percentile=EXCLUDED.seifa_irsd_state_percentile,
  seifa_ier_score=EXCLUDED.seifa_ier_score,
  seifa_ier_state_decile=EXCLUDED.seifa_ier_state_decile,
  seifa_ier_state_percentile=EXCLUDED.seifa_ier_state_percentile,
  coverage_status=EXCLUDED.coverage_status,
  missing_reasons=EXCLUDED.missing_reasons,
  retrieved_at=EXCLUDED.retrieved_at;

CREATE TABLE public.pharmacy_demographic_context (
  pharmacy_id UUID PRIMARY KEY REFERENCES public.pharmacy_premises(id) ON DELETE CASCADE,
  sa2_code_2021 TEXT,
  assignment_method TEXT NOT NULL DEFAULT 'point-in-polygon',
  geographic_resolution TEXT NOT NULL DEFAULT 'SA2 average; not a street-level catchment',
  coverage_quality TEXT NOT NULL CHECK (coverage_quality IN ('complete','partial','unavailable')),
  reference_year INTEGER,
  context JSONB NOT NULL DEFAULT '{}'::jsonb,
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.pharmacy_demographic_context ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.pharmacy_demographic_context TO anon,authenticated;
GRANT ALL ON public.pharmacy_demographic_context TO service_role;
CREATE POLICY public_reads_pharmacy_demographic_context
  ON public.pharmacy_demographic_context FOR SELECT TO anon,authenticated USING (true);

CREATE OR REPLACE FUNCTION public.refresh_pharmacy_demographic_context()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public
AS $$
DECLARE affected INTEGER;
BEGIN
  INSERT INTO public.pharmacy_demographic_context (
    pharmacy_id,sa2_code_2021,coverage_quality,reference_year,context,calculated_at
  )
  SELECT p.id,a.sa2_code_2021,COALESCE(d.coverage_status,'unavailable'),d.reference_year,
    CASE WHEN d.sa2_code_2021 IS NULL THEN
      jsonb_build_object(
        'warning','No source coverage',
        'assignment_method','point-in-polygon',
        'geographic_resolution','SA2 average; not a street-level catchment'
      )
    ELSE jsonb_build_object(
      'sa2_name_2021',d.sa2_name_2021,
      'census_total_population',d.census_total_population,
      'age_65_plus_count',d.age_65_plus_count,'age_65_plus_percent',d.age_65_plus_percent,
      'age_75_plus_count',d.age_75_plus_count,'age_75_plus_percent',d.age_75_plus_percent,
      'under_five_count',d.under_five_count,'under_five_percent',d.under_five_percent,
      'need_assistance_count',d.need_assistance_count,
      'need_assistance_percent',d.need_assistance_percent,
      'no_vehicle_dwellings_count',d.no_vehicle_dwellings_count,
      'no_vehicle_dwellings_percent',d.no_vehicle_dwellings_percent,
      'seifa_irsd_score',d.seifa_irsd_score,
      'seifa_irsd_state_decile',d.seifa_irsd_state_decile,
      'seifa_irsd_state_percentile',d.seifa_irsd_state_percentile,
      'seifa_ier_score',d.seifa_ier_score,
      'seifa_ier_state_decile',d.seifa_ier_state_decile,
      'missing_reasons',d.missing_reasons,
      'assignment_method','point-in-polygon',
      'geographic_resolution','SA2 average; not a street-level catchment',
      'census_measure','2021 Census count; not Estimated Resident Population',
      'source','Australian Bureau of Statistics, 2021 Census GCP and SEIFA 2021',
      'licence','CC BY 4.0'
    ) END,now()
  FROM public.pharmacy_premises p
  LEFT JOIN LATERAL (
    SELECT area.sa2_code_2021
    FROM public.dispensing_population_areas area
    WHERE p.location IS NOT NULL AND ST_Covers(area.boundary,p.location::geometry)
    ORDER BY ST_Area(area.boundary) LIMIT 1
  ) a ON true
  LEFT JOIN public.demographic_area_profiles d
    ON d.sa2_code_2021=a.sa2_code_2021 AND d.reference_year=2021
  ON CONFLICT (pharmacy_id) DO UPDATE SET
    sa2_code_2021=EXCLUDED.sa2_code_2021,
    coverage_quality=EXCLUDED.coverage_quality,
    reference_year=EXCLUDED.reference_year,
    context=EXCLUDED.context,
    calculated_at=EXCLUDED.calculated_at;
  GET DIAGNOSTICS affected=ROW_COUNT;

  UPDATE public.pharmacy_dispensing_potential potential
  SET raw_metrics=potential.raw_metrics || jsonb_build_object(
      'official_demographic_context',context.context,
      'demographic_coverage_quality',context.coverage_quality,
      'demographic_assignment_method',context.assignment_method
    ),
    warnings=CASE WHEN context.coverage_quality='complete' THEN potential.warnings
      ELSE array_append(
        array_remove(potential.warnings,'Official demographic coverage is partial'),
        'Official demographic coverage is partial'
      ) END,
    evidence_confidence=CASE
      WHEN context.coverage_quality='unavailable' THEN 'low'
      ELSE potential.evidence_confidence
    END
  FROM public.pharmacy_demographic_context context
  WHERE context.pharmacy_id=potential.pharmacy_id;
  RETURN affected;
END;
$$;
REVOKE ALL ON FUNCTION public.refresh_pharmacy_demographic_context() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_pharmacy_demographic_context() TO service_role;

CREATE OR REPLACE FUNCTION public.demographic_context_at_point(
  candidate_lat DOUBLE PRECISION,candidate_lng DOUBLE PRECISION
)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path=public
AS $$
  SELECT COALESCE((
    SELECT jsonb_build_object(
      'sa2_code_2021',d.sa2_code_2021,'sa2_name_2021',d.sa2_name_2021,
      'reference_year',d.reference_year,'coverage_status',d.coverage_status,
      'census_total_population',d.census_total_population,
      'age_65_plus_count',d.age_65_plus_count,'age_65_plus_percent',d.age_65_plus_percent,
      'age_75_plus_count',d.age_75_plus_count,'age_75_plus_percent',d.age_75_plus_percent,
      'under_five_count',d.under_five_count,'under_five_percent',d.under_five_percent,
      'need_assistance_count',d.need_assistance_count,
      'need_assistance_percent',d.need_assistance_percent,
      'no_vehicle_dwellings_count',d.no_vehicle_dwellings_count,
      'no_vehicle_dwellings_percent',d.no_vehicle_dwellings_percent,
      'seifa_irsd_score',d.seifa_irsd_score,
      'seifa_irsd_state_decile',d.seifa_irsd_state_decile,
      'seifa_ier_score',d.seifa_ier_score,
      'missing_reasons',d.missing_reasons,
      'assignment_method','point-in-polygon',
      'coverage_percentage',100,
      'geographic_resolution','SA2 average; not a street-level catchment',
      'census_measure','2021 Census count; not Estimated Resident Population'
    )
    FROM public.dispensing_population_areas area
    JOIN public.demographic_area_profiles d USING (sa2_code_2021)
    WHERE ST_Covers(
      area.boundary,
      ST_SetSRID(ST_MakePoint(candidate_lng,candidate_lat),4326)
    )
    ORDER BY ST_Area(area.boundary) LIMIT 1
  ),jsonb_build_object(
    'coverage_status','unavailable','warning','No source coverage',
    'assignment_method','point-in-polygon',
    'geographic_resolution','SA2 average; not a street-level catchment'
  ));
$$;
GRANT EXECUTE ON FUNCTION public.demographic_context_at_point(DOUBLE PRECISION,DOUBLE PRECISION)
  TO anon,authenticated;

CREATE OR REPLACE FUNCTION public.demographic_areas_in_viewport(
  west DOUBLE PRECISION,south DOUBLE PRECISION,east DOUBLE PRECISION,north DOUBLE PRECISION,
  metric TEXT
)
RETURNS TABLE (
  sa2_code_2021 TEXT,sa2_name_2021 TEXT,value NUMERIC,coverage_status TEXT,
  reference_year INTEGER,geometry JSONB
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path=public
AS $$
  SELECT d.sa2_code_2021,d.sa2_name_2021,
    CASE metric
      WHEN 'age65' THEN d.age_65_plus_percent
      WHEN 'age75' THEN d.age_75_plus_percent
      WHEN 'assistance' THEN d.need_assistance_percent
      WHEN 'disadvantage' THEN d.seifa_irsd_state_percentile
      WHEN 'no_vehicle' THEN d.no_vehicle_dwellings_percent
      ELSE NULL
    END,
    d.coverage_status,d.reference_year,
    ST_AsGeoJSON(ST_SimplifyPreserveTopology(area.boundary,0.002),5)::jsonb
  FROM public.demographic_area_profiles d
  JOIN public.dispensing_population_areas area USING (sa2_code_2021)
  WHERE metric IN ('age65','age75','assistance','disadvantage','no_vehicle')
    AND area.boundary && ST_MakeEnvelope(west,south,east,north,4326)
  ORDER BY d.sa2_code_2021
  LIMIT 600;
$$;
GRANT EXECUTE ON FUNCTION public.demographic_areas_in_viewport(
  DOUBLE PRECISION,DOUBLE PRECISION,DOUBLE PRECISION,DOUBLE PRECISION,TEXT
) TO anon,authenticated;

CREATE OR REPLACE FUNCTION public.scenario_evidence_at_point(
  p_lat DOUBLE PRECISION,p_lng DOUBLE PRECISION,p_radius_m INTEGER
) RETURNS JSONB
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT public.candidate_site_analysis(p_lat,p_lng,p_radius_m)
    || jsonb_build_object(
      'evidence_contract_version','wp21-v1',
      'captured_at',now(),
      'official_demographics',public.demographic_context_at_point(p_lat,p_lng),
      'missing_inputs',jsonb_build_array(
        'SA2 demographic averages are not precise site catchments',
        'Census population is not Estimated Resident Population',
        'absence of mapped external entities is not evidence that none exist'
      )
    );
$$;
REVOKE ALL ON FUNCTION public.scenario_evidence_at_point(
  DOUBLE PRECISION,DOUBLE PRECISION,INTEGER
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.scenario_evidence_at_point(
  DOUBLE PRECISION,DOUBLE PRECISION,INTEGER
) TO authenticated;

CREATE OR REPLACE FUNCTION public.public_data_freshness()
RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT jsonb_build_object(
    'latest_pharmacy_import',(SELECT max(fetched_at) FROM public.source_records
      WHERE source_kind IN ('healthdirect','osm')),
    'latest_supermarket_import',(SELECT max(fetched_at) FROM public.supermarkets),
    'latest_medical_centre_import',(SELECT max(fetched_at) FROM public.medical_centres),
    'abs_reference_period','2024 ERP; 2023–24 annual growth',
    'abs_demographic_reference_period','2021 Census and SEIFA; distinct from ERP',
    'abs_demographic_retrieved_at',(SELECT max(retrieved_at)
      FROM public.dispensing_demographic_sources WHERE reference_year=2021),
    'abs_demographic_coverage_areas',(SELECT count(*) FROM public.demographic_area_profiles),
    'schema_version','20260729143000'
  );
$$;
REVOKE ALL ON FUNCTION public.public_data_freshness() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.public_data_freshness() TO anon,authenticated;

SELECT public.refresh_pharmacy_demographic_context();
