/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildDotjsonRouteImport } from './routes/build[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAcquisitionsRouteImport } from './routes/app.acquisitions'
import { Route as AppCalibrationRouteImport } from './routes/app.calibration'
import { Route as AppDataSourcesRouteImport } from './routes/app.data-sources'
import { Route as AppRadarRouteImport } from './routes/app.radar'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as PharmacyIdRouteImport } from './routes/pharmacy.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildDotjsonRoute = BuildDotjsonRouteImport.update({
  id: '/build.json',
  path: '/build.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcquisitionsRoute = AppAcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => AppRoute,
} as any)
const AppCalibrationRoute = AppCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => AppRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const PharmacyIdRoute = PharmacyIdRouteImport.update({
  id: '/pharmacy/$id',
  path: '/pharmacy/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/build.json': typeof BuildDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/acquisitions': typeof AppAcquisitionsRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/radar': typeof AppRadarRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/security': typeof AppSecurityRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/build.json': typeof BuildDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/acquisitions': typeof AppAcquisitionsRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/radar': typeof AppRadarRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/security': typeof AppSecurityRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/build.json': typeof BuildDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/acquisitions': typeof AppAcquisitionsRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/data-sources': typeof AppDataSourcesRoute
  '/app/radar': typeof AppRadarRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/security': typeof AppSecurityRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/build.json'
    | '/sitemap.xml'
    | '/app/acquisitions'
    | '/app/calibration'
    | '/app/data-sources'
    | '/app/radar'
    | '/app/scenarios'
    | '/app/security'
    | '/pharmacy/$id'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/build.json'
    | '/sitemap.xml'
    | '/app/acquisitions'
    | '/app/calibration'
    | '/app/data-sources'
    | '/app/radar'
    | '/app/scenarios'
    | '/app/security'
    | '/pharmacy/$id'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/build.json'
    | '/sitemap.xml'
    | '/app/acquisitions'
    | '/app/calibration'
    | '/app/data-sources'
    | '/app/radar'
    | '/app/scenarios'
    | '/app/security'
    | '/pharmacy/$id'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildDotjsonRoute: typeof BuildDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PharmacyIdRoute: typeof PharmacyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build.json': {
      id: '/build.json'
      path: '/build.json'
      fullPath: '/build.json'
      preLoaderRoute: typeof BuildDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/acquisitions': {
      id: '/app/acquisitions'
      path: '/acquisitions'
      fullPath: '/app/acquisitions'
      preLoaderRoute: typeof AppAcquisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calibration': {
      id: '/app/calibration'
      path: '/calibration'
      fullPath: '/app/calibration'
      preLoaderRoute: typeof AppCalibrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-sources': {
      id: '/app/data-sources'
      path: '/data-sources'
      fullPath: '/app/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/radar': {
      id: '/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/pharmacy/$id': {
      id: '/pharmacy/$id'
      path: '/pharmacy/$id'
      fullPath: '/pharmacy/$id'
      preLoaderRoute: typeof PharmacyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcquisitionsRoute: typeof AppAcquisitionsRoute
  AppCalibrationRoute: typeof AppCalibrationRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppRadarRoute: typeof AppRadarRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcquisitionsRoute: AppAcquisitionsRoute,
  AppCalibrationRoute: AppCalibrationRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppRadarRoute: AppRadarRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildDotjsonRoute: BuildDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PharmacyIdRoute: PharmacyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
